apiVersion: apps/v1
kind: Deployment
metadata:
  name: soc-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soc-ui
  template:
    metadata:
      labels:
        app: soc-ui
    spec:
      containers:
        - name: ui
          image: app/soc-ui:ci
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: soc-ui
spec:
  selector:
    app: soc-ui
  ports:
    - port: 80
      targetPort: 80
