apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soc-ingress
spec:
  rules:
    - host: soc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: soc-ui
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: soc-api
                port:
                  number: 8000
